---
- name: Import datasource for grafana
  grafana_datasource:
    name: "monitoring"
    grafana_url: "http://localhost:{{ grafana_http_port }}"
    grafana_user: "{{ admin_user }}"
    grafana_password: "{{ admin_password }}"
    org_id: "1"
    ds_type: "prometheus"
    url: "http://172.17.0.1:9090"
  changed_when: false
